version: '3.9'

services:
  api:
    container_name: api
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: on-failure
    depends_on:
      - redis

  client:
    container_name: client
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - api

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - 6379:6379
    restart: always