import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'
import InputGroup from '../components/InputGroup'
import useAuthContext from '../hooks/useAuthContext'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const { efetuarLogin } = useAuthContext()
  const router = useRouter()
  const DASHBOARD_ROUTE = '/dashboard'

  const manipuladorLogin = async (event: React.ChangeEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (email && password) {
      try {
        await efetuarLogin({ email, password })
        await router.push(DASHBOARD_ROUTE)
      } catch (erro) {
        console.log(erro);
        
        alert('Erro ao tentar realizar o login, tente novamente.')
        setEmail('')
        setPassword('')
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Entrar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <form onSubmit={manipuladorLogin}>
            <h1>Login</h1>
            <InputGroup label="Email" htmlFor='email' name='email' type='email' value={email} onChange={(e) => setEmail(e.target.value)} />
            <InputGroup label="Senha" htmlFor='password' name='password' type='password' value={password} onChange={(e) => setPassword(e.target.value)} />
            <button type='submit'>Entrar</button>
          </form>
        </div>
      </main>
    </div>
  )
}
